on:
  push:
    branches:
      - main

jobs:
  jira-release-link:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Release name
        id: get-release-name
        run: |
          major=$(jq -r '.version' package.json | cut -d. -f1)
          echo "release-name=Connex Release $major" >> $GITHUB_OUTPUT

      - name: Create Jira release link
        uses: mantasmatij/jira-release-link@2.0.4
        with:
          jira-email: ${{ secrets.JIRA_EMAIL }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-domain: onstage.atlassian.net
          jira-project: SSYNC
          jira-ticket-key-prefix: SSYNC
          release-name: ${{ steps.get-release-name.outputs.release-name }}
          release-name-regex: "Connex Release ([0-9]+)"
