on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  jira-release-link:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Release name
        id: get-release-name
        run: |
          major=$(jq -r '.version' package.json | cut -d. -f1)
          echo "release-name=Connex Release $major" >> $GITHUB_OUTPUT

      - name: Create Jira release link
        uses: mantasmatij/jira-release-link@rewrite-to-JS
        with:
          jira-email: ${{ secrets.JIRA_EMAIL }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-domain: onstage.atlassian.net
          jira-project: SSYNC
          jira-ticket-key-prefix: SSYNC
          release-name: ${{ steps.get-release-name.outputs.release-name }}